## Test the environment `HerdEnv` of `herd_env.py`

In [1]:
import os
import numpy as np
import tensorflow as tf
from tf_agents.environments import utils
from tf_agents.trajectories.time_step import StepType
from tf_agents.trajectories import TimeStep
from tf_agents.policies import scripted_py_policy
from tf_agents.policies import random_py_policy
from tf_agents.policies import random_tf_policy
from tf_agents.policies import policy_saver
from tf_agents.metrics import py_metrics
from tf_agents.drivers import py_driver
from tf_agents.utils import common
from tf_agents.specs import tensor_spec

from tf_agents.networks import sequential

import sys
sys.path.insert(1, '/home/jovyan/Masterarbeit/reinforce-one/Environment')

In [2]:
from Env import Env
root_dir = '~/Masterarbeit/DDPG'
num_herds=2
total_population=300

### Train a DDPG Agent

In [3]:
def compute_avg_return(environment, policy, num_episodes=50, verbose=False):
  total_return = 0.0
  cullsteps = 0 
  for e in range(num_episodes):

    time_step = environment.reset()
    if isinstance(policy, scripted_py_policy.ScriptedPyPolicy):
        policy_state = policy.get_initial_state() # remember where in the script we were
    else:
        #print(policy.get_initial_state(batch_size=train_env.batch_size()))
        policy_state = policy.get_initial_state(batch_size=1) # other policies without memory
    episode_return = 0.0
    i=0
    while not time_step.is_last():
        i+=1
        action_step = policy.action(time_step, policy_state)
        for i in range (num_herds, num_herds*2):
            if action_step.action[0][i] > 0.1:
                cullsteps += 1
                break
        policy_state = action_step.state
        time_step = environment.step(action_step.action)

        state = None # TF environment from wrapper does not have get_state()
        episode_return += time_step.reward
        if verbose:
            print (f"episode {e:>2} step{i:>4} action: ", action_step.action, 
                   "state=", state, "obs=", time_step.observation, "reward=", time_step.reward)
    total_return += episode_return

  avg_return = total_return / num_episodes
  cullsteps /= num_episodes
  return avg_return, cullsteps

In [4]:

import functools
from tf_agents.networks import nest_map
from tf_agents.networks import sequential
from tf_agents.keras_layers import inner_reshape
from tf_agents.networks.sequential import Sequential
from tensorflow.keras.layers import Dense
from tf_agents.agents.ddpg import ddpg_agent
from tf_agents.environments import tf_py_environment
from tf_agents.replay_buffers import tf_uniform_replay_buffer
from tf_agents.trajectories import trajectory

In [5]:
num_iterations = 500000
replay_buffer_max_length = 100000
batch_size = 256
num_eval_episodes = 200
initial_collect_steps = 5000
collect_steps_per_iteration = 200
log_interval = 500
eval_interval = 500
threshhold_reset_interval = 50000
target_update_period = 5

In [6]:
train_env = tf_py_environment.TFPyEnvironment(Env(num_herds = num_herds, total_population = total_population, 
                                                  fix_episode_length = True, average_episode_length = 200))
eval_env = tf_py_environment.TFPyEnvironment(Env(num_herds = num_herds, total_population = total_population, 
                                                 fix_episode_length = True, average_episode_length = 200))

In [7]:
#kernel_initializer=tf.keras.initializers.RandomUniform(minval=-0.03, maxval=0.03)

#Make critic and actor net for ddpg

dense = functools.partial(
    tf.keras.layers.Dense,
    activation=tf.keras.activations.relu,
    kernel_initializer=tf.compat.v1.variance_scaling_initializer(
        scale=1./ 3.0, mode='fan_in', distribution='uniform'))


def create_identity_layer():
    return tf.keras.layers.Lambda(lambda x: x)


def create_fc_network(layer_units):
    return sequential.Sequential([dense(num_units) for num_units in layer_units])


def create_actor_network(fc_layer_units, action_spec):
    """Create an actor network for DDPG."""
    flat_action_spec = tf.nest.flatten(action_spec)
    if len(flat_action_spec) > 1:
        raise ValueError('Only a single action tensor is supported by this network')
    flat_action_spec = flat_action_spec[0]

    fc_layers = [dense(num_units) for num_units in fc_layer_units]

    num_actions = flat_action_spec.shape.num_elements()
    action_fc_layer = tf.keras.layers.Dense(
        num_actions,
        activation=tf.keras.activations.tanh,
        kernel_initializer=tf.keras.initializers.RandomUniform(
            minval=-0.003, maxval=0.003))

    scaling_layer = tf.keras.layers.Lambda(
        lambda x: common.scale_to_spec(x, flat_action_spec))
    return sequential.Sequential(fc_layers + [action_fc_layer, scaling_layer])


def create_critic_network(obs_fc_layer_units,
                          action_fc_layer_units,
                          joint_fc_layer_units):
    """Create a critic network for DDPG."""

    def split_inputs(inputs):
        return {'observation': inputs[0], 'action': inputs[1]}

    obs_network = create_fc_network(
        obs_fc_layer_units) if obs_fc_layer_units else create_identity_layer()
    action_network = create_fc_network(
        action_fc_layer_units
        ) if action_fc_layer_units else create_identity_layer()
    joint_network = create_fc_network(
        joint_fc_layer_units) if joint_fc_layer_units else create_identity_layer()
    
    value_fc_layer = tf.keras.layers.Dense(
        1,
        activation=None,
        kernel_initializer=tf.keras.initializers.RandomUniform(
            minval=-0.003, maxval=0.003))

    return sequential.Sequential([
        tf.keras.layers.Lambda(split_inputs),
        nest_map.NestMap({
            'observation': obs_network,
            'action': action_network
        }),
        nest_map.NestFlatten(),
        tf.keras.layers.Concatenate(),
        joint_network,
        value_fc_layer,
        inner_reshape.InnerReshape([1], [])
    ])

actor_fc_layers=(200, 150)
critic_obs_fc_layers=(200,)
critic_action_fc_layers=None
critic_joint_fc_layers=(150,)

actor_net = create_actor_network(actor_fc_layers, train_env.action_spec())
critic_net = create_critic_network(critic_obs_fc_layers,
                                       critic_action_fc_layers,
                                       critic_joint_fc_layers)

In [8]:
train_step_counter = tf.Variable(0)
global_step = tf.compat.v1.train.get_or_create_global_step()

agent = ddpg_agent.DdpgAgent(
        train_env.time_step_spec(),
        train_env.action_spec(),
        actor_network=actor_net,
        critic_network=critic_net,
        actor_optimizer=tf.compat.v1.train.AdamOptimizer(
            learning_rate=5e-5),    #1e-4
        critic_optimizer=tf.compat.v1.train.AdamOptimizer(
            learning_rate=5e-4),    #1e-3
        ou_stddev=0.2,
        ou_damping=0.15,
        target_update_tau=0.05,
        target_update_period=5,
        #dqda_clipping=dqda_clipping,
        td_errors_loss_fn=tf.compat.v1.losses.huber_loss,
        gamma=0.99,
        #reward_scale_factor=reward_scale_factor,
        #gradient_clipping=gradient_clipping,
        #debug_summaries=debug_summaries,
        #summarize_grads_and_vars=summarize_grads_and_vars,
        train_step_counter=global_step)

agent.initialize()

In [9]:
# agent.policy.trainable_variables

In [10]:
# manually initialize a reasonably good policy: kill both herds if the sum of observations is large
#W = np.array([[0, 3 ,0, 2],[0, 0, 3, 2,]])
#b = np.array([1, 0, 0, 0])
#q_net.layers[0].set_weights([W,b])
#agent.policy.trainable_variables

In [11]:
replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=agent.collect_data_spec,
    batch_size=train_env.batch_size,
    max_length=replay_buffer_max_length)

In [12]:
agent.collect_data_spec._fields

('step_type',
 'observation',
 'action',
 'policy_info',
 'next_step_type',
 'reward',
 'discount')

In [13]:
def collect_step(environment, policy, buffer):
    time_step = environment.current_time_step()
    action_step = policy.action(time_step)
    next_time_step = environment.step(action_step.action)
    traj = trajectory.from_transition(time_step, action_step, next_time_step)

    # Add trajectory to the replay buffer
    buffer.add_batch(traj)

def collect_data(env, policy, buffer, steps):
    for _ in range(steps):
        collect_step(env, policy, buffer)

random_policy = random_tf_policy.RandomTFPolicy(
    action_spec=train_env.action_spec(), time_step_spec=train_env.time_step_spec())
collect_data(train_env, random_policy, replay_buffer, initial_collect_steps)

In [14]:
# Dataset generates trajectories with shape [Bx2x...]
dataset = replay_buffer.as_dataset(
    num_parallel_calls=3, 
    sample_batch_size=batch_size, 
    num_steps=2).prefetch(3)

iterator = iter(dataset)
dataset

Instructions for updating:
Use `tf.data.Dataset.scan(...) instead
Instructions for updating:
Use `as_dataset(..., single_deterministic_pass=False) instead.


<PrefetchDataset shapes: (Trajectory(
{action: (64, 2, 4),
 discount: (64, 2),
 next_step_type: (64, 2),
 observation: (64, 2, 7),
 policy_info: (),
 reward: (64, 2),
 step_type: (64, 2)}), BufferInfo(ids=(64, 2), probabilities=(64,))), types: (Trajectory(
{action: tf.float32,
 discount: tf.float32,
 next_step_type: tf.int32,
 observation: tf.float32,
 policy_info: (),
 reward: tf.float32,
 step_type: tf.int32}), BufferInfo(ids=tf.int64, probabilities=tf.float32))>

In [ ]:
# Reset the train step
agent.train_step_counter.assign(0)

# Evaluate the agent's policy once before training.
avg_return = compute_avg_return(eval_env, agent.policy, num_eval_episodes)
returns = [avg_return]
# Initialize policy saver
saver = policy_saver.PolicySaver(agent.policy)
best_return = -1000000
root_dir = os.path.expanduser(root_dir)
policy_dir = os.path.join(root_dir, 'policy')

for _ in range(num_iterations):

  # Collect a few steps using collect_policy and save to the replay buffer.
  collect_data(train_env, agent.collect_policy, replay_buffer, collect_steps_per_iteration)

  # Sample a batch of data from the buffer and update the agent's network.
  experience, unused_info = next(iterator)
  train_loss = agent.train(experience).loss

  step = agent.train_step_counter.numpy()

  if step % log_interval == 0:
    print('step = {0:4>}: loss = {1:.4f}'.format(step, train_loss), end="\t")

  if step % eval_interval == 0:
    avg_return, cullsteps = compute_avg_return(eval_env, agent.policy, num_eval_episodes)
    print('step {0}: average return = {1:.1f} cullsteps = {2:.1f}'.format(step, avg_return.numpy().item(), cullsteps))
    returns.append(avg_return)
    if avg_return > best_return:
            best_return = avg_return
            print('New best return: ', best_return)
            saver.save(os.path.join(policy_dir, str(global_step.numpy())))
    elif step % threshhold_reset_interval == 0:
        best_return = -1000000

step = 1: loss = 0.6136	

step 1: average return = -160.5 cullsteps = 200.0
New best return:  tf.Tensor([-160.47134], shape=(1,), dtype=float32)


/opt/conda/lib/python3.9/site-packages/tensorflow/python/saved_model/nested_structure_coder.py:558: UserWarning: Encoding a StructuredValue with type tfp.distributions.Deterministic_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
  warnings.warn("Encoding a StructuredValue with type %s; loading this "


INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/1/assets


INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/1/assets


step 50: average return = -584.2 cullsteps = 200.0
step 100: average return = -584.9 cullsteps = 200.0
step = 500: loss = 0.3543	step = 1000: loss = 0.5120	step 1000: average return = -586.1 cullsteps = 0.0
step = 1500: loss = 1.3690	step = 2000: loss = 0.4447	step 2000: average return = -212.1 cullsteps = 200.0
step = 2500: loss = 0.1439	step = 3000: loss = 0.1844	

step 3000: average return = -31.3 cullsteps = 200.0
New best return:  tf.Tensor([-31.25108], shape=(1,), dtype=float32)
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/3000/assets


/opt/conda/lib/python3.9/site-packages/tensorflow/python/saved_model/nested_structure_coder.py:558: UserWarning: Encoding a StructuredValue with type tfp.distributions.Deterministic_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
  warnings.warn("Encoding a StructuredValue with type %s; loading this "
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/3000/assets


step = 3500: loss = 0.1811	step = 4000: loss = 0.2878	step 4000: average return = -40.0 cullsteps = 200.0
step = 4500: loss = 0.3687	step = 5000: loss = 0.1343	step 5000: average return = -49.6 cullsteps = 200.0
step = 5500: loss = 0.2839	step = 6000: loss = 0.3816	step 6000: average return = -49.5 cullsteps = 200.0
step = 6500: loss = 0.1196	step = 7000: loss = 0.3128	step 7000: average return = -41.5 cullsteps = 200.0
step = 7500: loss = 0.1922	step = 8000: loss = 0.2182	step 8000: average return = -70.6 cullsteps = 200.0
step = 8500: loss = 0.1754	step = 9000: loss = 0.1272	step 9000: average return = -70.3 cullsteps = 200.0
step = 9500: loss = 0.1922	step = 10000: loss = 0.1465	step 10000: average return = -81.0 cullsteps = 200.0
step = 10500: loss = 0.0917	step = 11000: loss = 0.1166	step 11000: average return = -114.8 cullsteps = 200.0
step = 11500: loss = 0.0868	step = 12000: loss = 0.1320	step 12000: average return = -89.6 cullsteps = 200.0
step = 12500: loss = 0.1295	step = 13

step 51000: average return = -152.5 cullsteps = 200.0
New best return:  tf.Tensor([-152.50243], shape=(1,), dtype=float32)
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/51000/assets


/opt/conda/lib/python3.9/site-packages/tensorflow/python/saved_model/nested_structure_coder.py:558: UserWarning: Encoding a StructuredValue with type tfp.distributions.Deterministic_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
  warnings.warn("Encoding a StructuredValue with type %s; loading this "
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/51000/assets


step = 51500: loss = 0.2036	step = 52000: loss = 0.1084	

step 52000: average return = -91.2 cullsteps = 200.0
New best return:  tf.Tensor([-91.24459], shape=(1,), dtype=float32)
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/52000/assets


/opt/conda/lib/python3.9/site-packages/tensorflow/python/saved_model/nested_structure_coder.py:558: UserWarning: Encoding a StructuredValue with type tfp.distributions.Deterministic_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
  warnings.warn("Encoding a StructuredValue with type %s; loading this "
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/52000/assets


step = 52500: loss = 0.0809	step = 53000: loss = 0.0402	step 53000: average return = -244.4 cullsteps = 200.0
step = 53500: loss = 0.1417	step = 54000: loss = 0.5640	step 54000: average return = -141.0 cullsteps = 200.0
step = 54500: loss = 0.5872	step = 55000: loss = 0.1606	step 55000: average return = -103.8 cullsteps = 200.0
step = 55500: loss = 0.0930	step = 56000: loss = 1.5282	step 56000: average return = -206.8 cullsteps = 200.0
step = 56500: loss = 0.1016	step = 57000: loss = 0.1964	step 57000: average return = -209.9 cullsteps = 200.0
step = 57500: loss = 0.3013	step = 58000: loss = 0.0813	step 58000: average return = -257.3 cullsteps = 200.0
step = 58500: loss = 0.4742	step = 59000: loss = 0.0298	step 59000: average return = -191.6 cullsteps = 200.0
step = 59500: loss = 0.1671	step = 60000: loss = 0.6056	step 60000: average return = -198.6 cullsteps = 200.0
step = 60500: loss = 0.1315	step = 61000: loss = 0.3816	step 61000: average return = -203.3 cullsteps = 200.0
step = 615

step 66000: average return = -82.7 cullsteps = 200.0
New best return:  tf.Tensor([-82.70242], shape=(1,), dtype=float32)
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/66000/assets


/opt/conda/lib/python3.9/site-packages/tensorflow/python/saved_model/nested_structure_coder.py:558: UserWarning: Encoding a StructuredValue with type tfp.distributions.Deterministic_ACTTypeSpec; loading this StructuredValue will require that this type be imported and registered.
  warnings.warn("Encoding a StructuredValue with type %s; loading this "
INFO:tensorflow:Assets written to: /home/jovyan/Masterarbeit/DDPG/policy/66000/assets


step = 66500: loss = 0.5562	step = 67000: loss = 0.6091	step 67000: average return = -101.9 cullsteps = 200.0
step = 68000: loss = 0.9871	step 68000: average return = -534.0 cullsteps = 200.0
step = 68500: loss = 0.0106	step = 69000: loss = 0.4432	step 69000: average return = -291.4 cullsteps = 200.0
step = 69500: loss = 0.8843	step = 70000: loss = 2.4337	step 70000: average return = -195.2 cullsteps = 200.0
step = 70500: loss = 1.1940	step = 71000: loss = 1.8093	step 71000: average return = -176.5 cullsteps = 200.0
step = 71500: loss = 1.3171	step = 72000: loss = 0.0072	step 72000: average return = -127.8 cullsteps = 200.0
step = 72500: loss = 0.7789	step = 73000: loss = 1.7922	step 73000: average return = -329.3 cullsteps = 200.0
step = 73500: loss = 0.9994	step = 74000: loss = 2.1446	step 74000: average return = -578.9 cullsteps = 200.0
step = 74500: loss = 1.9201	step = 75000: loss = 3.9910	step 75000: average return = -565.9 cullsteps = 200.0
step = 75500: loss = 3.1178	step = 760

In [ ]:
learned_reward, culleps = compute_avg_return(eval_env, agent.policy, num_episodes=500)
print ("reward of learned policy: ", learned_reward.numpy(), "cullsteps=", culleps)

In [ ]:
init_ts = eval_env.reset()

def get_action(obs):
    """ execute the learned policy network 
       obs:  one float for global time, one float for each herd - the time since last culling
    """
    _ts = TimeStep(tf.constant([0.]),
                   tf.constant([0.]),
                   tf.constant([1]),
                   tf.constant([obs]))
    # a = agent.collect_policy.action(_ts) # just to see how much is explored versus exploited
    a = agent.policy.action(_ts)
    return a.action.numpy().item()

In [ ]:
agent.policy

In [ ]:
# what the learned policy does on a grid of observations (5 steps per row&col)
'''A = [[get_action([.0, x,y])
 for y in np.arange(0.,1.,.05,np.float32)]
 for x in np.arange(0.,1.,.05,np.float32)]
A'''

### Play with parameters of manually designed q_network policy

In [ ]:
# W, b = agent.policy.trainable_variables
# W = W.numpy()
# b = b.numpy()
# print ("weights\n", W, "\nbias", b)

In [ ]:
# def nn(obs):
#    y = np.dot(obs, W)+b
#    return y

In [ ]:
# nn([0.5,.2])